# Generated by Django 5.2.6 on 2025-09-04 10:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='details',
            field=models.ManyToManyField(blank=True, to='shop.detail'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='card',
            name='details',
            field=models.ManyToManyField(blank=True, to='shop.detail'),
        ),
        migrations.AlterField(
            model_name='card',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos'),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='details',
            field=models.ManyToManyField(blank=True, to='shop.detail'),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos'),
        ),
        migrations.AlterField(
            model_name='jersey',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
