# Generated by Django 5.2.6 on 2025-09-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_jersey_size_itemincard_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='jersey',
            name='size',
        ),
        migrations.AddField(
            model_name='jersey',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, to='shop.size'),
        ),
    ]
