# Generated by Django 5.2.6 on 2025-09-07 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_size_remove_jersey_size_jersey_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemincard',
            name='chosen_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.size'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jersey',
            name='sizes',
            field=models.ManyToManyField(to='shop.size'),
        ),
    ]
