# Generated by Django 5.2.6 on 2025-09-07 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_itemincard_chosen_size_alter_jersey_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemincard',
            name='chosen_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.size'),
        ),
    ]
