# Generated by Django 4.2.24 on 2025-09-20 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_order_items_alter_order_user_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='arriving_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 27, 10, 41, 15, 938969, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.destination'),
            preserve_default=False,
        ),
    ]
