# Generated by Django 4.2.24 on 2025-09-20 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_order_arriving_date_alter_order_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arriving_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 27, 10, 43, 48, 363271, tzinfo=datetime.timezone.utc)),
        ),
    ]
