# Generated by Django 4.2.24 on 2025-09-22 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_order_arriving_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arriving_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 7, 19, 32, 4, 126746, tzinfo=datetime.timezone.utc)),
        ),
    ]
