# Generated by Django 4.2.24 on 2025-09-24 17:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_order_arriving_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='arriving_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 9, 17, 48, 41, 72942, tzinfo=datetime.timezone.utc)),
        ),
    ]
