# Generated by Django 4.2.24 on 2025-09-24 17:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_jersey_number_alter_order_arriving_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='arriving_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 9, 17, 50, 6, 223548, tzinfo=datetime.timezone.utc)),
        ),
    ]
