# Generated by Django 4.2.24 on 2025-09-24 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_jersey_number_alter_order_arriving_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jersey',
            name='player',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='arriving_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 9, 17, 56, 22, 636665, tzinfo=datetime.timezone.utc)),
        ),
    ]
