# Generated by Django 4.2.24 on 2025-09-24 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_jersey_player_alter_order_arriving_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jersey',
            name='number',
        ),
        migrations.RemoveField(
            model_name='jersey',
            name='player',
        ),
        migrations.AddField(
            model_name='itemincard',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemincard',
            name='player',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='player',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='arriving_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 9, 18, 34, 41, 670753, tzinfo=datetime.timezone.utc)),
        ),
    ]
