# Generated by Django 4.2.24 on 2025-09-25 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_shorts_remove_card_category_remove_card_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorts',
            name='sizes',
            field=models.ManyToManyField(to='shop.size'),
        ),
        migrations.AlterField(
            model_name='order',
            name='arriving_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 10, 20, 56, 19, 876054, tzinfo=datetime.timezone.utc)),
        ),
    ]
