# Generated by Django 4.2.24 on 2025-09-26 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_shorts_sizes_alter_order_arriving_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemincard',
            name='player',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='arriving_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 11, 17, 17, 24, 55091, tzinfo=datetime.timezone.utc)),
        ),
    ]
