# Generated by Django 4.2.24 on 2025-09-26 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_itemincard_player_alter_order_arriving_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arriving_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 11, 18, 19, 28, 162112, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='player',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
